### ISSUE TITLE
кококо

### ISSUE THREAD

**Issue by Grawl** [Ky6uk/PETOOH#5]
![bxaqse-iuaaj7m3 jpg-large](https://cloud.githubusercontent.com/assets/846774/5354822/7be814c6-7fd8-11e4-8c45-cbdca72b3f2e.jpeg)

**Comment by ccrystals** [comment]
> ![bxaqse-iuaaj7m3 jpg-large](https://cloud.githubusercontent.com/assets/846774/5354822/7be814c6-7fd8-11e4-8c45-cbdca72b3f2e.jpeg)
> 

true
